#Data
dataset_name: mmfi-csi
#DataLoader
modality: wifi-csi|rgb
#protocol1:14 actions:14 daily activities that are performed freely in space
#protocol2:13 actions: includes 13 rehabilitation exercisesthat are performed in a fixed location
#protocol3:all actions
protocol: protocol3
data_unit: window
split_to_use: random_split
init_rand_seed: 0

train_loader:
  batch_size: 128
validation_loader:
  batch_size: 32
dataset_root: /root/autodl-tmp/MMFI_DATA
output_folder: ./ckpt/
save_path: pose_weights
#Model
window_size : 10
step_size : 3
#Train
base_learning_rate: 0.0001
total_epoch: 50




random_split:
  ratio: 0.8
  random_seed: 0
  train_dataset:
    split: training
    scenes: None
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: None
    actions: all

cross_scene_split:
  train_dataset:
    split: training
    scenes: [ E01, E02, E03 ]
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: [ E04 ]
    subjects: None
    actions: all

cross_subject_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [ S01, S02, S03, S04, S06, S07, S08, S09, S11, S12, S13, S14, S16, S17, S18, S19, S21, S22, S23, S24, S26, S27, S28, S29, S31, S32, S33, S34, S36, S37, S38, S39 ]
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S05, S10, S15, S20, S25, S30, S35, S40 ]
    actions: all
#
#manual_split:
#  train_dataset:
#    split: training
#    scenes: None
#    subjects: [S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40]
#    actions: [A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]
#  val_dataset:
#    split: validation
#    scenes: None
#    subjects: [S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40]
#    actions: [A22, A23, A24, A25, A26, A27]
manual_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [S01,  S04]
    actions: [A01]
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S03]
    actions: [A01]


